- name:  printing conditions
  hosts: all
  become: true
  vars:
    roles: true
    designation: false
  tasks:
    - name: printing conditions
      ansible.builtin.debug:
        msg: role name is - devops engineer
      when: roles is defined


    - name: printing conditions
      ansible.builtin.debug:
        msg: role name is - devops engineer
      when: designation is defined
