- name: aws parameters
  hosts: localhost
  connection: local
  tasks:
    - name: fetch the values
      ansible.builtin.debug:
           msg: {{ lookup('amazon.aws.aws_ssm', 'rds.dev.database_name', region='us-east-1a' ) }}