- name: install nginx
  hosts: WEB
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: start nginx
      ansible.builtin.yum:
        name: nginx
        state: restarted
        enable: yes