- name: install nginx
  hosts: localhost
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: started nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enable: yes