- name: practice
  hosts: all
  connection: local
  become: true
  tasks:
    - name: start nginx
      ansible.builtin.yum:
        name: nginx
        state: installed


    - name: restarted nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes