- name: install nginx
  hosts: web
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: started nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes

- name: install nginx
  hosts: web
  become: true
  roles:
    - sample


- name: print values
  hosts: web
  become: true
  vars:
    URL: google.com
  tasks:
    - name: print values
      ansible.builtin.debug:
        msg: url = {{ URL }}
